### ISSUE TITLE
Fix format of stemplot document

### ISSUE THREAD

**Issue by mrkn** [red-data-tools/unicode_plot.rb#48]

**Comment by nanobowers** [comment]
hi @mrkn , i noticed with the latest pull that you have a customized version of yard to fix the module_function decorator issue, very nice!
Now that I can properly generate the documentation html with YARD, I can see the issue with the documentation for stemplot - I must have thought I was writing Markdown synax instead of RDoc syntax (oops)

If you would like, i can fix this, since i was the person who broke it.

**Comment by mrkn** [comment]
@nanobowers Could you please submit the candidate change as a pull-request?
